version: '3.4'

services:
  mongo:
    image: mongo:3.6.8
    env_file:
      - .env
    volumes:
      - "./entrypoints/mongo/:/docker-entrypoint-initdb.d/"
      - anthor-data:/data/db
  app:
    ports:
      - "${DOCKER_PORT}:${PORT}"
    build: .
    env_file:
      - .env

volumes:
  anthor-data:
    external: true
